<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <!-- SEO: meta tags generated by SEOTools (per-page values override site defaults) -->
        @if (class_exists('\Artesaos\SEOTools\Facades\SEOMeta'))
            {!! SEOMeta::generate() !!}
            {!! OpenGraph::generate() !!}
            {!! Twitter::generate() !!}
            {!! JsonLd::generate() !!}
        @endif

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Company favicon (if uploaded, fallback to default) -->
        @php
            // Use CompanyHelper to resolve favicon (handles storage route fallback)
            $favicon = \App\Helpers\CompanyHelper::favicon();
        @endphp
        <link rel="icon" type="image/png" href="{{ $favicon }}" />

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts & Styles -->
        @php
            try {
                // Use Vite when available (production build or dev server)
                echo vite(['resources/css/app.css', 'resources/js/app.js']);
            } catch (\Throwable $e) {
        @endphp
                <link rel="stylesheet" href="{{ asset('css/app.css') }}">
                <script src="{{ asset('js/app.js') }}" defer></script>
        @php
            }
        @endphp

        <!-- Styles -->
        @livewireStyles
    </head>
    <body class="font-sans antialiased">
        <x-banner />

        <div class="min-h-screen bg-gray-50 md:bg-gray-100">
            @livewire('navigation-menu')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow-sm md:shadow">
                    <div class="max-w-7xl mx-auto py-4 px-3 sm:py-6 sm:px-6 lg:px-8">
                        <div class="text-lg sm:text-xl font-semibold text-gray-900">
                            {{ $header }}
                        </div>
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main class="px-3 sm:px-4 md:px-6">
                @isset($slot)
                    {{ $slot }}
                @else
                    @yield('content')
                @endisset
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>
